// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/nordew/UploadApp/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ImageStorage is an autogenerated mock type for the ImageStorage type
type ImageStorage struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, id
func (_m *ImageStorage) GetAll(ctx context.Context, id string) ([]entity.Image, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Image, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Image); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySize provides a mock function with given fields: ctx, id, size
func (_m *ImageStorage) GetBySize(ctx context.Context, id string, size int) (*entity.Image, error) {
	ret := _m.Called(ctx, id, size)

	if len(ret) == 0 {
		panic("no return value specified for GetBySize")
	}

	var r0 *entity.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*entity.Image, error)); ok {
		return rf(ctx, id, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *entity.Image); ok {
		r0 = rf(ctx, id, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, id, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, image
func (_m *ImageStorage) Upload(ctx context.Context, image entity.Image) error {
	ret := _m.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Image) error); ok {
		r0 = rf(ctx, image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImageStorage creates a new instance of ImageStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageStorage {
	mock := &ImageStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
