version: '3.1'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
    - '9000:9000'
    - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_STORAGE_USE_HTTPS=False

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  minio_data:
  mongodb_data: