PGHost: "localhost"
PGPort: "5432"
PGUser: "postgres"
PGDBName: "postgres"
PGSSLMode: "disable"
PGPassword: "131212"
Salt: '@*($djjasd'
Secret: 'norman!28'
MinioHost: 'localhost'
MinioPort: 9000
MinioUser: 'minio'
MinioPassword: 'minio123'
Rabbit: 'amqp://localhost:5672'
StripeKey: 'sk_test_51OIclQI5OJGi55AFooWML165wo9zcprZikk6fYd9OSKUxWHsQXyHaAxgrKheIwOrF6o1RIZHroOPdFVrYTd3VjS500QzejjMjt'